/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author madus
 */
public class RoomDetails extends javax.swing.JFrame {

    /**
     * Creates new form RoomDetails
     */
    public RoomDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jCheckBox19 = new javax.swing.JCheckBox();
        jButton8 = new javax.swing.JButton();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jButton12 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ROOM DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 318, 46));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SMALL CLOSE.jpg"))); // NOI18N
        jButton1.setText("jButton1");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(997, 13, 50, 46));

        jLabel2.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("NUMBER OF FAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 152, 343, 44));

        jLabel3.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jLabel3.setText("NUMBER OF LIGHTS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 214, 343, 44));

        jLabel4.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("NUMBER OF CHAIRS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 276, 343, 45));

        jLabel5.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jLabel5.setText("NUMBER OF TABLE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 339, 343, 44));

        jLabel6.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("NUMBER OF BEDS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 401, 343, 46));

        jLabel7.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jLabel7.setText("NUMBER OF STUDENT");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 466, 343, 45));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 255));
        jLabel8.setText("STUDENT ID ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 77, 335, 45));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 78, 343, 45));

        jButton2.setBackground(new java.awt.Color(255, 153, 51));
        jButton2.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("SEARCH");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 77, 131, 45));

        jCheckBox1.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox1.setText("1");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 152, 54, 44));

        jCheckBox2.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox2.setText("2");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 340, 54, 42));

        jCheckBox3.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox3.setText("3");
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 339, 54, 44));

        jCheckBox4.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox4.setText("1");
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 339, 54, 44));

        jCheckBox5.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox5.setText("2");
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 152, 54, 44));

        jCheckBox6.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox6.setText("3");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 152, 54, 44));

        jCheckBox7.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox7.setText("1");
        getContentPane().add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 214, 54, 45));

        jCheckBox8.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox8.setText("2");
        getContentPane().add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 214, 54, 45));

        jCheckBox9.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox9.setText("3");
        getContentPane().add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 214, 54, 45));

        jCheckBox10.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox10.setText("1");
        getContentPane().add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 277, 54, 44));

        jCheckBox11.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox11.setText("2");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 276, 54, 44));

        jCheckBox12.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox12.setText("3");
        getContentPane().add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 277, 54, 42));

        jCheckBox13.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox13.setText("1");
        getContentPane().add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 401, 54, 46));

        jCheckBox14.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox14.setText("1");
        getContentPane().add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 466, 54, 45));

        jCheckBox15.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox15.setText("2");
        getContentPane().add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 401, 54, 47));

        jCheckBox16.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox16.setText("2");
        getContentPane().add(jCheckBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 470, 54, 45));

        jCheckBox17.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox17.setText("3");
        getContentPane().add(jCheckBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 401, 54, 47));

        jCheckBox18.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox18.setText("3");
        getContentPane().add(jCheckBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 471, 54, 43));

        jButton3.setBackground(new java.awt.Color(255, 153, 51));
        jButton3.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("SAVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 152, 131, 44));

        jButton4.setBackground(new java.awt.Color(255, 153, 51));
        jButton4.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 102));
        jButton4.setText("SAVE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 214, 131, 44));

        jButton5.setBackground(new java.awt.Color(255, 153, 51));
        jButton5.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 102));
        jButton5.setText("SAVE");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 276, 131, 45));

        jButton6.setBackground(new java.awt.Color(255, 153, 51));
        jButton6.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 102, 102));
        jButton6.setText("SAVE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 339, 131, 44));

        jButton7.setBackground(new java.awt.Color(255, 153, 51));
        jButton7.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 102, 102));
        jButton7.setText("SAVE");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 401, 131, 46));

        jCheckBox19.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox19.setText("4");
        getContentPane().add(jCheckBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 471, 54, 43));

        jButton8.setBackground(new java.awt.Color(255, 102, 0));
        jButton8.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 102, 51));
        jButton8.setText("SAVE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 469, 131, 46));

        jCheckBox20.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox20.setText("4");
        getContentPane().add(jCheckBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 153, 52, 43));

        jCheckBox21.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox21.setText("4");
        getContentPane().add(jCheckBox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 214, 52, 38));

        jCheckBox23.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox23.setText("4");
        jCheckBox23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox23ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 340, 54, 43));

        jCheckBox24.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox24.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox24.setText("4");
        jCheckBox24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox24ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox24, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 403, 54, 43));

        jCheckBox22.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox22.setText("4");
        getContentPane().add(jCheckBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 276, 52, 44));

        jButton9.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(153, 0, 153));
        jButton9.setText("DELETE");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(926, 524, 121, 47));

        jButton10.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(153, 0, 153));
        jButton10.setText("SAVE");
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(926, 460, 121, 46));

        jButton11.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(153, 0, 153));
        jButton11.setText("EDIT");
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(926, 591, 121, 45));

        jCheckBox25.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox25.setForeground(new java.awt.Color(51, 51, 51));
        jCheckBox25.setText("1");
        jCheckBox25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox25ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox25, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 533, 54, 51));

        jCheckBox26.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox26.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox26.setForeground(new java.awt.Color(51, 51, 51));
        jCheckBox26.setText("2");
        getContentPane().add(jCheckBox26, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 533, 54, 51));

        jCheckBox27.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox27.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox27.setForeground(new java.awt.Color(51, 51, 51));
        jCheckBox27.setText("3");
        jCheckBox27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox27ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox27, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 533, 54, 51));

        jCheckBox28.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox28.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox28.setForeground(new java.awt.Color(51, 51, 51));
        jCheckBox28.setText("4");
        getContentPane().add(jCheckBox28, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 533, 54, 51));

        jButton12.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 102, 0));
        jButton12.setText("SAVE");
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 533, 131, 51));

        jLabel9.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 153));
        jLabel9.setText("CUPBOARD");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 300, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/leaves_wood_background_color_18265_2560x1600.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 1110, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jCheckBox23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox23ActionPerformed

    private void jCheckBox24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox24ActionPerformed

    private void jCheckBox25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox25ActionPerformed

    private void jCheckBox27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox27ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
